services:
  web:
    build: .
    image: oc-lettings:local
    ports:
      - "8000:8000"
    environment:
      DEBUG: "False"
      ALLOWED_HOSTS: "localhost,127.0.0.1"
      SECRET_KEY: "${SECRET_KEY}"
      SENTRY_DSN: ""
      SENTRY_ENVIRONMENT: "docker-local"
